### ISSUE TITLE
Description / Mention of Longer lived branch workflow

### ISSUE THREAD

**Issue by brntbeer** [github/training-kit#247]
I've taught a few people a version of the GitHub flow that uses longer lived branches, wondering if there's a place in the workflow section of Advanced for us to describe this?

This is also the workflow that we'll be using for this repo moving forward i believe.

**Comment by crichID** [comment]
@brntbeer this issue is super stale. I have added this to the backlog in the training repo and will close this out. If you would like it re-opened, please feel free to do so!
