### ISSUE TITLE
Incorporate abstract/chapter summary in slides

### ISSUE THREAD

**Issue by jordanmccullough** [github/training-kit#258]
Based on a [Training team discussion](https://github.com/github/training-team/issues/987#issuecomment-60163956), the curriculum "slides" would benefit from a summary or objectives "what you'll learn" list at the very beginning of the content.

![slide-summary](https://cloud.githubusercontent.com/assets/352082/4756743/e3a47434-5acf-11e4-8132-f9808e09d109.png)

**Comment by jordanmccullough** [comment]
Now that the [checklist feature](https://github.com/github/training-kit/issues/258#issuecomment-60952005) first-draft is implemented [here](https://github.com/github/training-kit/pull/292#issuecomment-68621622), closing this issue in favor of the https://github.com/github/training-kit/pull/292.

**Comment by matthewmccullough** [comment]
:metal: implementation, @jordanmccullough.
