### ISSUE TITLE
Organization and Team slide order flip?

### ISSUE THREAD

**Issue by brntbeer** [github/training-kit#281]
In https://training.github.com/kit/foundations/#surveying-the-github-platform, as we get to the end of the major feature set, we mention teams before organizations.

Should this be reversed? I often think about this from the top down: " An organization acts like a user, but connects individuals together to repositories through teams."

Otherwise, im open to suggestions on how I could improve the way in which i talk about orgs and teams! :smile:

**Comment by johnnyhall481** [comment]
[adequacy-japan-factsheet_en_2019_1.pdf](https://github.com/github/training-kit/files/5649302/adequacy-japan-factsheet_en_2019_1.pdf)
@technicalpickles
