### ISSUE TITLE
Mix of tabs and spaces in stylesheets

### ISSUE THREAD

**Issue by brntbeer** [github/training-kit#297]
I noticed we have a mix of tabs and spaces in some of the stylesheets. @jordanmccullough what are your thoughts on adding those to spaces?

**Comment by jordanmccullough** [comment]
Gasp! Not sure how, but happy to clean it up, for sure. Thanks for opening the issue, @brntbeer.

**Comment by brntbeer** [comment]
haha, not a problem! just figured you worked well with issues, so i thought i'd open this one up!
