### ISSUE TITLE
Organizing history for optimal workflow breaks TOC

### ISSUE THREAD

**Issue by brntbeer** [github/training-kit#302]
We currently have two `<h2>` elements for the section of "organizing history for optimal workflow. This also shows as two TOC elements on the right hand side.

![screen shot 2015-01-06 at 11 37 24 pm](https://cloud.githubusercontent.com/assets/45141/5640993/22ed056c-95fd-11e4-8786-1803e22cef64.png)

**Comment by jordanmccullough** [comment]
Hit this snag in a class today also. Fixing.

Thanks @brntbeer for opening the issue on this.

**Comment by crichID** [comment]
@brntbeer @jordanmccullough is this issue OK to ❌

**Comment by jordanmccullough** [comment]
:x: away.
