### ISSUE TITLE
user.name and user.email in intermediate start out without flags, and don't work

### ISSUE THREAD

**Issue by brntbeer** [github/training-kit#307]
https://training.github.com/kit/intermediate/ starts out listing the `user.name` and `user.email`, but no flag for the level of setting it at.

The slides should reflect that this needs `--global` for it.

**Comment by matthewmccullough** [comment]
👍

**Comment by crichID** [comment]
It seems this was addressed in #311 and merged. Closing this!

**Comment by brntbeer** [comment]
The images still apparently don't show it correctly, but since we're moving past this and i can't find where the images actually live in this repository, im fine with closing this! thanks!
