### ISSUE TITLE
Found some minor issues in the Spanish translation of 'github-foundations.md'

### ISSUE THREAD

**Issue by andres-mancera** [github/training-kit#308]
I noticed a few minor issues (misspellings, typos) over in the [Spanish translation of 'github-foundations.md'](https://github.com/github/training-kit/blob/master/workbooks/es/github-foundations.md).  I would like to submit a pull request in order to fix them.  Is this is welcome contribution right now?

**Comment by matthewmccullough** [comment]
Yes indeed, @andres-mancera ! It is most welcome!

**Comment by crichID** [comment]
Looks like this issue has already been addressed in #309. Closing!
