### ISSUE TITLE
TOC hidden in Firefox

### ISSUE THREAD

**Issue by ElizabethN** [github/training-kit#310]
I'm using Firefox 34.0.5 and the TOC ghosts away when my cursor is not hovering. It works :a:-:ok: in Chrome and Safari. 

This is what I mean:

![training bug](https://cloud.githubusercontent.com/assets/57594/5928128/690aef92-a646-11e4-800f-06dcd5cc26f7.gif)

Hope that helps!

**Comment by jordanmccullough** [comment]
Thanks for opening this @ElizabethN. Definitely looks like it needs a fix. :sparkles:

**Comment by jordanmccullough** [comment]
Will come back to this if this continues. `Backlog`-ing for now.
