### ISSUE TITLE
Outdated cheat sheet (PT) PDF file

### ISSUE THREAD

**Issue by felipedau** [github/training-kit#326]
It's been a while since the [PDF file](https://github.com/github/training-kit/blob/master/downloads/pt/github-git-cheat-sheet.pdf) of the Cheat Sheet in Portuguese was built (Jun 9, 2014), but I'm not sure if there is a schedule to build these things. It happens that it does not have the latest version of the [md file](https://github.com/github/training-kit/blob/master/downloads/pt/github-git-cheat-sheet.md) (Oct 17, 2014).

In the PDF file, one of the descriptions is in Spanish:

> ```$ git branch [nome-do-branch]```
> Crea una nueva rama

In the source file, it is correct though:

> ```$ git branch [nome-do-branch]```
> Cria um novo branch

That was the only issue I noticed.

Thanks for the kit!

**Comment by brntbeer** [comment]
Good find! Because the PDF files a bit harder to update, we were thinking of leaning more towards web-only view for these cheat sheets.

Is the translation in the `.md` file correct thought?

**Comment by felipedau** [comment]
> Good find! Because the PDF files a bit harder to update, we were thinking of leaning more towards web-only view for these cheat sheets.

Sounds good. By the way, if people ask for the PDF files, could they be hosted
somewhere and then use Webhooks to keep them synced?

> Is the translation in the `.md` file correct thought?

Actually there are some things I just noticed that could be fixed/improved.

There are some words I'm not happy with, but I couldn't think of a better
translation. It happens that I just found out that there is a [pt-br
version](https://git-scm.com/book/pt-br/v1) of the Pro Git book and they have
good stuff there.

Should I discuss the changes here or go ahead modify it, make a PR and then
someone revises that?

Should it stress that it's Brazilian Portuguese?

Also, I found another bug in the PDF files. The EN version has the following
command:

> `$ git config --global color.ui auto`
> Enables helpful colorization of command line output

The PT version has the command as well, but the description is the same as the
one used for `user.email`:

> `$ git config --global color.ui auto`
> Configura o email que você quer ligado as suas transações de commit

However, none of the `.md` files have that command :O

Thanks!

Ps: I just cloned the repo and was reading the master branch.

**Comment by brntbeer** [comment]
> By the way, if people ask for the PDF files, could they be hosted
> somewhere and then use Webhooks to keep them synced?

Ideally i'd love it if the printed version of these web pages looked good enough to be thought of as PDF files. Otherwise we'd love to keep the PDFs here. I just currently know we don't have time to put together too many PDFs, very open to others adding it though




> go ahead modify it, make a PR and then someone revises that?
> 
> Should it stress that it's Brazilian Portuguese?

I fully encourage you to submit PRs to revise it. Maybe even making a mention at the top of the file somewhere that it's Brazilian Portuguese (as i don't know the difference between types of Portuguese) to just give a notice to the reader.



> Also, I found another bug in the PDF files. The EN version has the following
> command:
> However, none of the `.md` files have that command :O

It does appear that the description to using `git config --global color.ui auto` is wrong in the `pt` version of the pdf. In fact all of the `.pdf` files list this command, but they're not in the `.md` version. My vote is to remove them from the pdf's completely, as it's a default in modern versions of Git. Great catch!

**Comment by felipedau** [comment]
> Ideally i'd love it if the printed version of these web pages looked good enough to be thought of as PDF files. Otherwise we'd love to keep the PDFs here. I just currently know we don't have time to put together too many PDFs, very open to others adding it though

Got it.

> I fully encourage you to submit PRs to revise it. Maybe even making a mention at the top of the file somewhere that it's Brazilian Portuguese (as i don't know the difference between types of Portuguese) to just give a notice to the reader.

Alright, I'll do that once I have it ready.

> It does appear that the description to using `git config --global color.ui auto` is wrong in the `pt` version of the pdf. In fact all of the `.pdf` files list this command, but they're not in the `.md` version. My vote is to remove them from the pdf's completely, as it's a default in modern versions of Git. Great catch!

I agree! Doesn't look like it's necessary.

Thanks!

**Comment by felipedau** [comment]
Finally finished what I think can improve the PT cheat sheet: #328

I did not mention this issue there because although I proposed the changes
here, they're not about the same topic. I think I will leave  this issue
open until the PDF thing is solved. Or maybe another one should be open to
address all the PDF files.

Thanks!

**Comment by brntbeer** [comment]
@felipedau i agree this issue should stay open until the problems in the original post are answered.

Taking a look at your PR now, thanks!

**Comment by brntbeer** [comment]
Sorry for closing and re-opening. 

> I think I will leave  this issue open until the PDF thing is solved.

@felipedau any update on this? I think keeping this open for the one specific piece to fix would be good.

**Comment by felipedau** [comment]
> @felipedau any update on this? I think keeping this open for the one specific piece to fix would be good.

@brntbeer since I last posted to this issue, the `pdf` file was still outdated and that's why I left it open. However, as you mentioned in #334, the link points to an updated `html` page and I should've probably closed this one because there is no `pdf` file anymore.

Maybe a new one should be opened to find a general way to make these things build automatically to keep them synced, because it looks like it is done manually, right? I just edited a couple `md` and `html` files and I do not know how exactly the *training-kit* works, so correct me if I am wrong. If you think it is worth making some kind of automatic build system, we should probably open this new issue and discuss to find a solution. I honestly don't know where to start.

**Comment by brntbeer** [comment]
> If you think it is worth making some kind of automatic build system, we should probably open this new issue and discuss to find a solution. I honestly don't know where to start.

I agree that we should close this down and open an issue to at least speculate ways to get .pdfs to automatically get updated, or some alternative. Honestly if there was a "Print" button on the `.html` pages that printed the PDF, i think that would do.

@felipedau would you like to get started on that issue and close this one?

**Comment by felipedau** [comment]
> I agree that we should close this down and open an issue to at least speculate ways to get .pdfs to automatically get updated, or some alternative. Honestly if there was a "Print" button on the .html pages that printed the PDF, i think that would do.

That's a great idea! I think that most of it can be done just by changing the CSS. It shouldn't be too hard.

> @felipedau would you like to get started on that issue and close this one?

Sure. Are there any other resources that would be useful to be available as `pdf` files as well, or just the cheat sheets?

**Comment by felipedau** [comment]
Can I also make an issue to turn all the cheat sheets into `html` pages?

The whole website (including those pages) are synced with this repo, right? Or it still has to be built just like the `pdf` files?

**Comment by brntbeer** [comment]
> Sure. Are there any other resources that would be useful to be available as pdf files as well, or just the cheat sheets?

@felipedau i think just the cheat sheets or now. We can end up making the subversion migration one into pdf later and kind of continue to iterate on it.



> Can I also make an issue to turn all the cheat sheets into html pages?

If you mean turn all of the `pdf`s into html, sure. The interesting part is that we already do have markdown converting it into html, so I wonder if some of that work is already done for us. Would be nice if the markdown pages we already have could stay for ease of editing. Maybe make it so if someone wanted to just see a pdf, they could switch to a different view or the html had a link to pdf every time (i wouldnt be against that i don't think =)

**Comment by brntbeer** [comment]
> The whole website (including those pages) are synced with this repo, right? Or it still has to be built just like the pdf files?

@felipedau sorry, i missed this. yes, everything that's at training.github.com/kit is on this repo itself. When we make the changes here (and probably test them locally) the @github/training-teachers would have to merge it into a private repo to get it deployed.

**Comment by felipedau** [comment]
> @felipedau i think just the cheat sheets or now. We can end up making the subversion migration one into pdf later and kind of continue to iterate on it.

Sounds good.

> If you mean turn all of the pdfs into html, sure. The interesting part is that we already do have markdown converting it into html, so I wonder if some of that work is already done for us. Would be nice if the markdown pages we already have could stay for ease of editing.

I noticed that the Brazilian Portuguese, Chinese and Italian cheat sheet links point to the `html` pages with that new layout, but the others don't. They are `pdfs` with the old layout. I would like that all those links pointed to an `html` page with the new layout. That will also make it easier to keep them synced with the repo and the `md` files should stay there, it's a lot easier to manage the content.

> Maybe make it so if someone wanted to just see a pdf, they could switch to a different view or the html had a link to pdf every time (i wouldnt be against that i don't think =)

In my opion the `pdf` should be used as an offline copy of the `html` page, so making a link that generates a nice printable version of it that can be saved as a `pdf` is probably enough for the users. What do you think?

> @felipedau sorry, i missed this. yes, everything that's at training.github.com/kit is on this repo itself. When we make the changes here (and probably test them locally) the @github/training-teachers would have to merge it into a private repo to get it deployed.

Cool! Then it seems that the easiest way to do what we want is doing `md -> html -> pdf`.

Finally, I would like to open the following issues:

- Provide all the cheat sheets as `html` pages
- Make the cheat sheets printable as `pdf` files with the same `html` layout

**Comment by crichID** [comment]
> Then it seems that the easiest way to do what we want is doing `md -> html -> pdf`.

@felipedau thank you for your thoughtful comments. I completely agree with you and would :heart: to see this level of consistency among these resources. Please feel free to open a PR containing these changes!

**Comment by felipedau** [comment]
> @felipedau thank you for your thoughtful comments. I completely agree with you and would ❤️ to see this level of consistency among these resources. Please feel free to open a PR containing these changes!

Sorry @crichID I think I was waiting for @brntbeer's confirmation and forgot this issue. Unfortunately I need help to make those changes, so I opened new issues ( #379, #380). This one can finally be closed!
