### ISSUE TITLE
Proposal to contribute

### ISSUE THREAD

**Issue by exalted** [github/training-kit#339]
Hey there!

Nothing specific; I wanted to ask whether would you appreciate my contribution on whatever task you may need help with in your priority list right now (I mean _anything_ really).

I :heart: git & GitHub + teaching, so I figured: this repo would be a nice place to do some work around that.

For instance, [`git-lfs`](http://github.com/github/git-lfs) doesn’t seem to have much coverage. I would love to make some code contributions to `git-lfs` as well, but I am not sure if I could find time to learn Go language in short-term, instead _maybe_ we could prep some training material first...

So there it goes, let’s discuss where to go from here. :beers:

**Comment by matthewmccullough** [comment]
@exalted my knowledgeable @github/training-teacher colleagues will be able to offer topic guidance, but let me just say how wonderful it is to have your offer. We certainly will find a way to make great use of your help!

**Comment by exalted** [comment]
Standing by sir! 👌😀

**Comment by loranallensmith** [comment]
@exalted Thank you so much for offering a :hand: in helping us craft some :sparkles: training material.  

I'm happy to help support your contributions in any way I can.  I also wanted to loop in @technoweenie to this thread, for his :boom: knowledge of Git LFS and its most immediate needs in terms of training content.

**Comment by exalted** [comment]
Thx for awesome welcomings to all of you.
Should I simply wait some sort of a draft idea/plan/idea at this point or...?
🖐
--
Ali




On Fri, Dec 4, 2015 at 7:54 AM -0800, "Allen Smith" <notifications@github.com> wrote:












@exalted Thank you so much for offering a  in helping us craft some  training material.  



I'm happy to help support your contributions in any way I can.  I also wanted to loop in @technoweenie to this thread, for his  knowledge of Git LFS and its most immediate needs in terms of training content.

**Comment by loranallensmith** [comment]
@exalted Sorry for the delayed response. :bow:  I was chatting with @technoweenie today and wanted to see how you felt about moving this conversation over into the [`github/git-lfs`](https://github.com/github/git-lfs) repository to :guitar: on it more.

It would be :sparkles: to have help adding to the [documentation](https://github.com/github/git-lfs/tree/master/docs) that currently exists, but the repository's Wiki might also be a great place to experiment with drafting some training material.

As a first step, you could open up an issue to gather questions that the docs could answer.  If you open up an issue there, feel free to @mention me.  I'm happy to support you however I can. :+1:

**Comment by exalted** [comment]
As I opened an issue at https://github.com/github/git-lfs feel free to close this one please, if you think there’s not much left here to discuss.

However please keep in mind anything else `git`-related (not necessarily `git-lfs`) was/is also fine as far as my contribution goes.

Thanks @loranallensmith and @matthewmccullough. :beers:

**Comment by loranallensmith** [comment]
@exalted Thanks a bunch for opening up that issue.  I'll close this one down for now!

Please feel free to reopen if the need arises!  :+1:

**Comment by exalted** [comment]
:+1:

**Comment by exalted** [comment]
:clap:
