### ISSUE TITLE
Main column of git cheat sheet overlaps footer

### ISSUE THREAD

**Issue by benlk** [github/training-kit#342]
<img width="756" alt="screen shot 2016-01-05 at 3 05 50 pm" src="https://cloud.githubusercontent.com/assets/1754187/12126266/2d8dd5ac-b3be-11e5-9538-5335323e2d8b.png">

On https://training.github.com/kit/downloads/github-git-cheat-sheet, the content overlaps the footer.

The browser here is Chrome's latest, at about 750px wide.

**Comment by brntbeer** [comment]
@benlk thanks for finding this! Super weird.

I'm guessing this may have something to do with how we render the columns to stay usable. I'll take a look at tinkering with it unless i can convince @jordanmccullough (or yourself if you know how!) to help me with it =)

**Comment by brntbeer** [comment]
@benlk got a fix coming in #343, there was an issue with extra html coming into this mix.
