### ISSUE TITLE
contribute to cheat sheet

### ISSUE THREAD

**Issue by moeinrahimi** [github/training-kit#347]
hi
I'm almost new to git and github concepts, i would like to contribute github cheat sheet and make a persian translation cheat sheet file, I would appreciate if someone explain me how to do that, should i edit the cheat-sheet.md file and then what.
thanks

**Comment by moein-rahimi** [comment]
anyone there to help me with this? please?

**Comment by brntbeer** [comment]
Oops, sorry @moein-rahimi, I was traveling yesterday and forgot to respond to this. I showed it off to some colleagues but forgot to reply!

I would **love** it if you submitted any type of new cheat sheet to this repository. You could look at how to do that by copying the pattern of some of the other markdown files in the `downloads/` directory. Like https://github.com/github/training-kit/blob/master/downloads/de/github-git-cheat-sheet.md. 

To get started, create a fork of this repository, and then create a new folder/file combination for the language of your choice. I would assume most people just copy the content over to their new file and then start translating everything except the git commands themselves.

Let me know if you need any other assistance with this workflow. very exciting

**Comment by loranallensmith** [comment]
@moein-rahimi If it helps at all, you may want to take a look at #156, where a contributor submitted an Arabic translation that included right-to-left rendering of the text.  

I think Persian is a RTL language.  Is that right?

**Comment by moein5** [comment]
ok, to start i must first fork this repository and create a new folder for the language and inside the folder just like the other languages in the downloads folder.
i'll create a .md file for translation, that's all it takes? nice, just one more question how do you convert the .md file to pdf version ?
@loranallensmith thanks, yes, it's a rtl language, that's great there is a RTL translation. it helps me a lot. thank you again

**Comment by moein-rahimi** [comment]
ok, i'll do like you said, what should i do after that?
 just one more question how do you convert the .md file to pdf version ?
@loranallensmith thanks, yes, it's a rtl language, that's great there is a RTL translation. it helps me a lot. thank you again

**Comment by brntbeer** [comment]
@moein-rahimi dont worry about pdf for now, when you finish the .md file, you'd have to convert that to .pdf using a template that we have.

@jordanmccullough is the template for making the pdf something we could upload to the repo?

**Comment by brntbeer** [comment]
> ok, i'll do like you said, what should i do after that?

sorry @moein-rahimi i missed this piece, did you mean what you should you do after you make the .md file? Let me know if you'd need some help doing this on a local git client (like a terminal or GitHub Desktop) and opening a pull request

**Comment by jordanmccullough** [comment]
> @jordanmccullough is the template for making the pdf something we could upload to the repo?

@brntbeer, It certainly is. Let me know if I can assist with providing the source material and `.ai` file. Also happy to provide the document in `.svg` for a more portable and editable format.

**Comment by brntbeer** [comment]
@jordanmccullough great. I'll keep you in mind in the future. If you ever want to just drop those files into the repository that may even be a good step

**Comment by amitkumarj441** [comment]
Can i translate the Github training kit in local languages? This can help other people who don't have proper english knowledge! One more thing, can i create a video of training kit in other local languages?
Please let me know where i can initiate a PR for this!

**Comment by brntbeer** [comment]
@amitkumarj441 you can absolutely contribute to the training kit translations! If you'd like, you can add them to the [`downloads/`](https://github.com/github/training-kit/tree/master/downloads) folder and we can make sure they get all good to go!

**Comment by amitkumarj441** [comment]
Hi @brntbeer ,

Glad to hear you!
I'm gonna initiating a PR(pdf & .md) for the same in local language!

Cheers,
Amit Kumar Jaiswal

**Comment by brntbeer** [comment]
@amitkumarj441 sounds good! I'd focus on just the `.md` version first. It may be easiest as the templates for the `.pdf`s aren't in this repo

**Comment by crichID** [comment]
This issue has been hanging around for a while, I am going to go ahead and close it out but please feel free to reopen if there are additional questions!
