### ISSUE TITLE
Squirrel vs. Rocket difference?

### ISSUE THREAD

**Issue by hcanna** [github/training-kit#348]
Good Morning @github/training-teachers ... for the GitHub Flow, https://guides.github.com/introduction/flow/ ,  we are using the Squirrel for the the deploy icon, and in the Teacher Outline, https://training.github.com/kit/modules/COLL-00_Introducing-github.html?teacher=hcanna ... 

Can you help me understand the differences between the two deploys? Thanks

**Comment by crichID** [comment]
@hcanna great catch! Yes, we should definitely address visual inconsistencies like this as we work to revise our curriculum. Let's not worry about it in this version since I am hopeful we will have the new version posted very soon!
