### ISSUE TITLE
Contributing to Git Cheat Sheet by adding useful commands

### ISSUE THREAD

**Issue by hkasera** [github/training-kit#352]
Hello,

I use Git on a daily basis and I absolutely :heart:  it.  There are a few commands that are quite handy. I was going through the [cheat sheet](https://training.github.com/kit/downloads/github-git-cheat-sheet.pdf) and I found out that those are missing in the sheet.

For example - Whenever we create a new branch, we checkout to the same branch. A useful command for that is `git checkout -b <branch name>`

This is just one example. There are many such handy commands that I would love to see in the existing cheat sheet so that other developers can take advantage of the same.

Let me know if this is a welcome contribution to the repository!

Cheers,
Harshita

**Comment by brntbeer** [comment]
@hkasera thanks for opening this issue!

I agree that `git checkout -b <branch name>` is pretty critical and a very common command. Could you think of others?

Im wondering if there's a good way to get more commands added to this repo without necessarily having to have us need to re-print PDFs, or change a bunch of languages. Open to suggestion from @github/training as well

**Comment by hkasera** [comment]
I can think of a few more  -

* `git merge --abort`
* `git checkout .`
* `git stash save <stash name>`
* `git stash pop <stash name>`
* `git checkout <stash@{0}> — <filename>`
* `git apply <patch file>`
* `git log --pretty=oneline`

**Comment by brntbeer** [comment]
@hkasera i agree some of those commands (especially checkout differences and merge options) would be great. However, I don't know that they'd fit into the single sheet (front and back even). Whatya think about a second type of sheet, like a more advanced cheat sheet?

**Comment by hkasera** [comment]
@brntbeer Yes, I think a second cheat sheet is a good idea :+1:. In that cheat sheet we could have the above commands as well as a few more like tagging related commands.

**Comment by brntbeer** [comment]
@hkasera I'd love to ship some good first iteration of these commands so we could at least record something about them. 

I don't love that the cheat sheets are in https://github.com/github/training-kit/tree/master/downloads, but would you like to create a plain markdown file titled like `advanced-git-github-cheat-sheet.md` and add some of these commands and a short description for? The first iteration doesn't need to be formatted like the other sheets, we can change that later. A bulleted list for now would do!

**Comment by hkasera** [comment]
@brntbeer That sounds great! I would be happy to do that. 

I will fork the repo, add the commands in the new file as you mentioned and send a PR for the same.

**Comment by hkasera** [comment]
@brntbeer I added a basic version of the [advanced cheat sheet](https://github.com/hkasera/training-kit/blob/master/downloads/github-git-advanced-cheat-sheet.md) in the forked repo. Can you take a look at [that](https://github.com/hkasera/training-kit/blob/master/downloads/github-git-advanced-cheat-sheet.md) and let me know if it looks good?

**Comment by brntbeer** [comment]
@hkasera looks good! feel free to send a pull request over to this repo to get that started

**Comment by hkasera** [comment]
@brntbeer created a [PR](https://github.com/github/training-kit/pull/353) for the same :+1:

**Comment by hkasera** [comment]
@brntbeer Thanks for merging the changes! :smile: 
Now that we have the first version out, we should plan for the next step :thought_balloon: 
I was thinking to add all the commands which we use like tagging and diff between branches etc. I would need your advice on how to begin with the next step.

**Comment by brntbeer** [comment]
@hkasera if you'd like you can just continue to submit PRs to that file at any time really. That'd probably be the best way: get every advanced command you can think of recorded, and then we can decide on how it should look in a more permanent format.

**Comment by hkasera** [comment]
@brntbeer Sure will do that!

**Comment by brntbeer** [comment]
@hkasera i'm going to close this issue, as we have a pretty good workflow for getting additional content now into that advanced cheat sheet. Let's do any future coordination in the pull requests that we work on together!

**Comment by hkasera** [comment]
Sure @brntbeer :+1: Thank you!!
