### ISSUE TITLE
New cheat sheet for PT-PT

### ISSUE THREAD

**Issue by bitoiu** [github/training-kit#357]
Hey @brntbeer,

Sorry to mention you directly, didn't see a `traning-kit` team and didn't want to over do it with `training`. Is there an appetite for a PT-PT cheat sheet?

I fully understand why we went for PT-BR to start with, it's follows the industry trend due to the high number of technical folks of Brazil vs Portugal.

I would be keen on working on the PT-PT translation, I just wanted to know if there's valid reasons not to do so, instead of starting the work right away.

:octocat::heart:

**Comment by brntbeer** [comment]
@bitoiu no worries, @mentioning the `@github/training-teachers` is always a safe bet though.

For some additional background see #334 and #328 , and specifically the start of convo here: https://github.com/github/training-kit/pull/328#issuecomment-126795227.



> I would be keen on working on the PT-PT translation, I just wanted to know if there's valid reasons not to do so, instead of starting the work right away.

😍 😍 😍 😍 😍 😍 😍 😍 😍 😍 😍 😍 😍 😍 😍 please do, contributions always welcome
