### ISSUE TITLE
README.md: broken links

### ISSUE THREAD

**Issue by guntbert** [github/training-kit#358]
In the paragraph 

>The slides align with the Foundations, Intermediate, and Advanced classes delivered by the GitHub Training team.

all three links are broken.

**Comment by H-Darji** [comment]
All three links for **Foundations, Intermediate, Advanced** are already provided in the paragraph after it **at lines 23, 24, 25**. 
See the following snapshot:

> **Snapshot:**

![1](https://cloud.githubusercontent.com/assets/14276147/15171985/659c8158-1770-11e6-8659-2f3e4d5300af.JPG)

**Comment by guntbert** [comment]
@H-Darji thank you for the clarification.
