### ISSUE TITLE
Releases of training kit

### ISSUE THREAD

**Issue by brianamarie** [github/training-kit#362]
### Releases of training kit

_Pertinent to the issue [Offline documentation](https://github.com/github/solutions-engineering/issues/2032) in Solutions Engineering_

@github/services-training, @jordanmccullough Is there a reason that we stopped doing this, other than transition of responsibilities? 

> The build of this repository is fully automated through several shell scripts. To perform a build of the materials identical to that of our continuous integration server, from the top directory of this project, run `./_buildscripts/cibuild` and then inspect the output in the _site directory.

> The `_buildscripts/makerelease` script produces a zip bundle for offline use of these materials. Pre-built releases are available at https://github.com/github/training-kit/releases

As a newer member of the team, I'd ❤️ some background information on this feature and its role in offline build protocol. 😄

**Comment by jordanmccullough** [comment]
@brianamarie, While I cannot speak to when specifically release efforts "stopped," what I can share is the approach for this buildscript approach.

- Every Release had an associated tracking issue (.e.g. this one from [January 2015](https://github.com/github/training-kit/issues/290))
- [Releases aligned with specific updates, improvements](https://github.com/github/training-kit/releases)

As the materials stabilized, there may have been less focus on the releases and just continually shipping the tune ups and efficiently as possible.

Happy to explore this more if needed.

**Comment by brianamarie** [comment]
@jordanmccullough Thank you for the comment on this! I would love to pick your brain more about this to more fully understand. Would it be possible to schedule a time to 👖 on this topic either tomorrow or sometime next week? If so, please feel free to put something in my calendar at a time most convenient for you. 😄

**Comment by jordanmccullough** [comment]
> sometime next week? 

@brianamarie, 👍 .

Looking forward to the calendar invite so we can discuss. :sparkles:
