### ISSUE TITLE
Unable to run cibuild script on Mac OS X 10.11.4

### ISSUE THREAD

**Issue by eriksaline** [github/training-kit#363]
Running `./_buildscripts/cibuild` in bash produces the following error.  Seems to be related, https://github.com/ffi/ffi/issues/461.  Applying the fix mentioned in the issue then gives an additional rake aborted error because the bundle script is not found.

rake aborted!
LoadError: Could not open library 'c': dlopen(c, 5): image not found.
Could not open library 'libc.dylib': dlopen(libc.dylib, 5): image not found
/Users/maddog/training-kit/vendor/gems/ruby/2.0.0/gems/ffi-1.9.6/lib/ffi/library.rb:133:in `block in ffi_lib'

**Comment by jbjonesjr** [comment]
@eriksaline I've solved this before, let me see if I can find my notes.

**Comment by jbjonesjr** [comment]
Ok, so from my previous experience with this issue:

update your GemFile to include the following line at the top:
`gem 'ffi', git: 'git://github.com/ffi/ffi.git', branch: :elcapt`

This is actually a dependency based on `typhoeus` in `html-proofer`, but that modification should be enough for you. 

When i was running either `ruby` or `irb` on a file, I did have to make sure it knew the environment, so do something like `bundle exec ruby script_file.rb`. Keep that in mind if you are testing locally.

**Comment by crichID** [comment]
@jbjonesjr thank you for your helpful troubleshooting! @eriksaline please let us know if you need additional assistance.
