### ISSUE TITLE
Make `html` cheat sheets printable as `pdf` files and update links

### ISSUE THREAD

**Issue by felipedau** [github/training-kit#379]
The discussion started in #326 where @brntbeer and I were trying to find a way to keep the cheat sheet builds synced with the source code (`.md` files). We believe that providing all the cheat sheets in `html` (the same way the Brazilian Portuguese, Chinese and Italian currently are) is a lot easier than `pdf` because with `html` it is possible to generate the `pdf`.

I just built the website locally and noticed that the `html` cheat sheets are being built. Then I confirmed that they are online as well:

```
https://services.github.com/kit/downloads/github-git-cheat-sheet.{pdf,html}
```

Both are online, but the former is the one referenced in the website. Instead of accessing the `pdf` links, one can manually go to the `html`. Therefore, if we just change the links to point to the `html` pages, it should work. We might need to check each cheat sheet to make sure the `html` is being built correctly.

In my opinion, in order to close this issue we basically need to update the links in `index.html`. Can someone confirm that this solution is correct?

**Comment by brntbeer** [comment]
> In my opinion, in order to close this issue we basically need to update the links in index.html. Can someone confirm that this solution is correct?

The problem is that attempting to print (or download, for that matter) the `.html` version does not look the same as the `.pdf` version (as mentioned in https://github.com/github/training-kit/issues/380). Because all of the pages have a `.md` file, they automatically generate the `.html` version. The idea would be to add better CSS for the printing sheets.

@felipedau can we close https://github.com/github/training-kit/issues/380 so that we can just track this effort into a single issue? there's a lot of duplication of text and next-steps in both of these issues. This issue should address 2 things: 

- Make `.html` pages print / download and be viewed the same way as the `.pdf` (the way they are viewed on the web)
- Make all links be `.html`

**Comment by felipedau** [comment]
On Tue, Jun 14, 2016 at 05:57:09AM -0700, Brent Beer wrote:
> @felipedau can we close https://github.com/github/training-kit/issues/380 so that we can just track this effort into a single issue? there's a lot of duplication of text and next-steps in both of these issues. This issue should address 2 things: 
> 
> - Make `.html` pages print / download and be viewed the same way as the `.pdf` (the way they are viewed on the web)
> - Make all links be `.html`

Yes, absolutely! I just split them because some of the cheat sheets
are already available only in `.html` and I thought that it would not
be a problem to do the same for all of them (#379). Once we figured
out how to print them properly, then the `.pdf` versions would be back
(#380).

Do you want me to close #380 and edit the title of this one to join
them?

**Comment by brntbeer** [comment]
> Do you want me to close #380 and edit the title of this one to join
> them?

@felipedau that'd be awesome! thank you 😄

**Comment by felipedau** [comment]
More info from #380:

The `pdf` should actually be built by the users by printing it with the browser. However, changes to the style of the page should make it possible (probably modifying the `@media print` queries in `css`), because currently it is removed:

![printed-ggcs](https://cloud.githubusercontent.com/assets/4574368/15994160/52f5b9d0-30ec-11e6-8d13-825467f47f53.png)

If this works, a download/print button should be added to the page so that users know it is available.

Can someone confirm that is possible and point us to the right direction if so?

**Comment by zalew16** [comment]
#326

**Comment by zalew16** [comment]
#380

**Comment by brianamarie** [comment]
> Can someone confirm that is possible and point us to the right direction if so?

This is a great question. @JasonEtco Could you help us answer this question and possibly find a path forward?

**Comment by pavankumargep** [comment]
h

**Comment by brianamarie** [comment]
It seems this effort has gone stale. I'm going to close this issue, but if anyone would like to contribute these changes to make this possible, please re-open this issue or open a pull request.
