### ISSUE TITLE
Study

### ISSUE THREAD

**Issue by houweilei** [github/training-kit#381]
@defunkt  hi,I'm a beginner.
![0 06-14-15-14-24 1](https://cloud.githubusercontent.com/assets/12932110/16170532/b9c4ef50-3588-11e6-82f6-fd388bcc7e6c.gif)
![2x](https://cloud.githubusercontent.com/assets/12932110/16170538/e72b6140-3588-11e6-94a9-17a23b6dd077.png)

**Comment by brianamarie** [comment]
Hi @houweilei! 👋 If you're looking for someplace to find beginner resources, I suggest looking here:
- [GitHub's Training courses](https://services.github.com/training/)
- [GitHub Guides](https://guides.github.com/)

If you have questions, don't be afraid to ask for help! I am going to close this issue now, but you still will be able to comment on it if you want to. 😄
