### ISSUE TITLE
User-reported Brazilian Portuguese Translation Error on Git Cheat Sheet

### ISSUE THREAD

**Issue by wordsoup** [github/training-kit#389]
A user contacted Support regarding a translation mistake for the Brazilian Portuguese Git Cheat Sheet:

**Opened from Halp**: [Translation mistake on Git Cheat Sheet] (https://halp.githubapp.com/inboxes/accounts/discussions/1c7f7fd2687611e68af95b431e32665f) 

> There's a translation mistake in Brazilian Portuguese version of Git Cheat Sheet.
On Group Changes topic, the descriptin of $ git branch [branch-name] is in Spanish. Could you fix this?

> Thanks a lot,

> Bruna

Thanks in advance to anyone available to take a look. 👀

**Comment by hectorsector** [comment]
Happy to help @wordsoup! I don't speak Brazilian Portuguese, though.

Perhaps we can find someone that speaks Brazilian Portuguese to help! I believe @bitoiu speaks Portuguese from Portugal so I'm not sure he'll be able to help either, but let's start there 😄

**Comment by bitoiu** [comment]
Hi @hectorsector :wave:

The user is right, but it just seems the PDF is outdated:

<img width="309" alt="screen shot 2016-09-03 at 21 05 10" src="https://cloud.githubusercontent.com/assets/1192590/18227379/2bbe43ea-721a-11e6-8029-9a1fe6617152.png">

But in the MD: https://github.com/github/training-kit/blob/master/downloads/pt_BR/github-git-cheat-sheet.md#mudanças-em-grupo it's all good.

So I guess it's just a matter of re-generating the PDF, and then updating the training-kit on the services site project.

Does that seem ok?

:octocat::heart:
