### ISSUE TITLE
Contribution to Cheat Sheets

### ISSUE THREAD

**Issue by gh0st** [github/training-kit#399]
I'd like to contribute to the cheat sheet collection by providing not only cheat sheets for Git but cheat sheets for using bash. Could you point me in the right direction for this? I've already forked and cloned this repo and I'm ready to get started. Shall I just create a PR once I'm ready? I'd also hope that it can be created into it's own unique .pdf file with it's own .ai header and etc. Perhaps once I'm done with the bash cheat sheet I will make one or two for popular IDEs like Atom.

**Comment by crichID** [comment]
@gh0st you have the perfect username for this time of year!

> I've already forked and cloned this repo and I'm ready to get started. Shall I just create a PR once I'm ready?

Yes, this is exactly how you would do it! 

As you probably noticed, the cheat sheets are in: https://github.com/github/training-kit/tree/master/downloads. You would start the cheat sheet as a .md file and then open the PR. Once the .md gets the :+1: and merged in, we will work on creating the PDF.

Good luck and I am looking forward to seeing some new cheat sheets!

**Comment by crichID** [comment]
@gh0st hopefully these are well under way, I am going to close out this issue to keep things in the repository tidy, but please feel free to reopen if you have questions or (even better) open a PR with the new cheat sheet!
