### ISSUE TITLE
Video Branding

### ISSUE THREAD

**Issue by hollenberry** [github/training-kit#418]
In building out a summary video/slide deck for Introduction to GitHub, it occurred to me that any video we produce would benefit from strong branding.

## Why?

  - Point more roads to our On Demand curriculum (especially since we've seen that videos get more traction than the courses). 
  - Keep our YouTube channel better organized.
  - Indicate fresh/new content.

## What does this look like?
  - A consistent title slide. Octocat + GitHub On Demand + Course Title 
  - A strong color scheme.
  - A consistent Screenflow Template?
  - A consistent ending (Thanks for Watching)
  - Optional? Consistent icon formatting when used in videos. (For example, bold octicons versus regular). 

## Some Items for Discussion
  - Are we comfortable sharing this branding for use in the community if volunteers want to produce videos? Should there be a division?
  - What color do you think On Demand feels like? Purple is taken by Enterprise, Green is taken by Classroom, and I believe Blue is used already. 

@loranallensmith I'd love to set up a call with you and whomever is interested from @github/services-training to go over the potential of this idea. I believe that we discussed the idea of a strong brand in past video conversations, and your assistance/guidance would be incredibly valuable here. 

Update: Had a Slack conversation with Allen and this conversation is going to happen tomorrow if you're interested in joining (12/2).

**Comment by brianamarie** [comment]
In general 👍 ✨  to this! I'm not sure how involved the design team would want to be, but it may be worth a ping.

**Comment by hollenberry** [comment]
- [x] A consistent title slide. Octocat + GitHub On Demand + Course Title
- [x] A strong color scheme.
- [x] A consistent Screenflow Template?
- [x] A consistent ending (Thanks for Watching)
- [ ] Optional? Consistent icon formatting when used in videos. (For example, bold octicons versus regular).

Quick update! Closing this out as the above has been completed. 

@loranallensmith is a hero. I appreciate you almost as much as your daughter appreciates 🌮 s
