### ISSUE TITLE
Add Fork me on GitHub Ribbon

### ISSUE THREAD

**Issue by crichID** [github/training-kit#435]
Wouldn't it be great if our courses pointed people back to their source? What do you think about adding a [Fork me on GitHub](https://github.com/blog/273-github-ribbons) ribbon?

/cc @github/services-training

**Comment by beardofedu** [comment]
I like this one:

![](https://camo.githubusercontent.com/a6677b08c955af8400f44c6298f40e7d19cc5b2d/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f677261795f3664366436642e706e67)
