### ISSUE TITLE
Training Idea: GitHub API Development

### ISSUE THREAD

**Issue by alrightjones** [github/training-kit#439]
While thumbing through some of our [On-Demand Training](https://services.github.com/on-demand/), the question arose: Do we have GitHub API development training? From what I can gather, the answer is no. I'd like to propose adding a GitHub API training course to our offering so we can start to lower the barrier for developers to become GitHub integrators.

A few questions we should probably answer out of the gate:

1. Was there a reason we avoided the effort previously?
2. Does this fit in with the initiatives of the training team for 2017?
3. If so, is this better suited for a [live format](https://services.github.com/resources/) or [on-demand](https://services.github.com/on-demand/)?
4. What is typically needed from other teams and individuals to create training content?

CC @github/business-development @github/platform-interface

**Comment by brianamarie** [comment]
@alrightjones Thank you for surfacing this!!! An API course has been on the radar but knowing there is strong interest definitely moves it up and helps it become a priority! 

@github/services-training What do you think?

**Comment by hectorsector** [comment]
> What do you think?

Yes!

![](http://i.giphy.com/l41YrxL7e1EE6zDDG.gif)

**Comment by kdaigle** [comment]
I'd quadruple love if this course could focus on GraphQL as that will eventually become the one-true-way to integrate with GitHub. Otherwise, let us know how we can be of help and take into account our roadmap as part of this.

**Comment by crichID** [comment]
@alrightjones thank you for sharing this idea and getting the ball rolling. GitHub's API is really the first I have worked with and I am thankful for the awesome documentation at: https://developer.github.com/v3/ and for the [development guides](https://developer.github.com/guides/) that contain several cool projects.  

We could also point to [this book](http://shop.oreilly.com/product/0636920043027.do) by Chris Dawson and Ben Straub as a great resource for further learning.

One additional thing to consider, right now GitHub uses a REST API, but [GraphQL](https://developer.github.com/early-access/graphql/) is in early access. As I am typing this sentence, the awesome @kdaigle pops in with the same note -- but I would also :heart: to see us consider focusing on GraphQL!

**Comment by crichID** [comment]
A few GraphQL resources:

- [Start with this video from Universe with @kdaigle and Facebook](https://youtu.be/wPPFhcqGcvk)
- Check out the Learn section of http://graphql.org/
- GraphQL blog has a cool section at the top for people who are learning: http://graphql.org/community/#blogs

**Comment by alrightjones** [comment]
@kdaigle I think there is a real need for GraphQL training as well, but should we start with REST or GraphQL? How far away is GraphQL away from being Production ready?

**Comment by kdaigle** [comment]
@alrightjones we're still determining the exact timelines but we're expecting it to be full production in "months". I don't think it's worth the effort to cover REST as those materials will likely become outdated/deprecated quickly.

**Comment by allthedoll** [comment]
Hi all! 👋 

I've been working on an API course offering that is given by the @github/services-engineering team, and we've had two successful deliveries with another scheduled next week. As of now, these are intended to be live-only deliveries, but the course next week @migarjo and I will be piloting a remote delivery to see if it's viable.

I don't want to rain on anyone's parade, but I feel that offering this API course or something similar through on-demand will potentially take money away from the engineering team's offering.

Thoughts, @mattcantstop?

**Comment by alrightjones** [comment]
@allthedoll that's awesome. Would you mind sharing your material with us? I'd love to see what you have. 

> I feel that offering this API course or something similar through on-demand will be difficult

What are the difficult parts? I've never built on-demand or live training material for GitHub, so I'm unfamiliar with the perceived challenges.

**Comment by crichID** [comment]
> What are the difficult parts? I've never built on-demand or live training material for GitHub, so I'm unfamiliar with the perceived challenges.

@alrightjones this is a great question! Ultimately, there are certain types of learning that are better suited for certain types of delivery. The API course @allthedoll is referring to is actually a highly consultative course. Our Services Engineering team works side by side with the user to understand their API needs and guide them in crafting solutions. That type of experience would be impossible via on-demand. With on-demand, we would strive to provide a more general understanding and the activities are more one-size-fits-all.  I definitely think this is the right discussion to be having as we figure out the appropriate scope for this course so keep it coming!

**Comment by swinton** [comment]
We also developed a 90 minute hands-on API class for Universe Training Day, please let me know if anyone here needs access to the repo:

### [Blasting-off-with-the-GitHub-API](https://github.com/universetrainingday/Blasting-off-with-the-GitHub-API)

**Comment by hectorsector** [comment]
> scheduled next week to test remote delivery. I don't want to rain on anyone's parade, but I feel that offering this API course or something similar through on-demand will be difficult--we're not even sure how delivering remotely is going to go.

@allthedoll ✋ I'm volunteering if you need any advice/best practices for remote delivery

**Comment by alrightjones** [comment]
@swinton bringing this one back to life since we are starting to scope possible educational partnerships for API / GitHub integration training. 

1. Do you have any updates on your [Universe Training Kit](https://github.com/universeworkshops/Blasting-off-with-the-GitHub-API)?
2. Does it include GraphQL? If not, how can we incorporate?
3. Have we thought about parallel distribution channels for the material? I have a few ideas about this and would love to share with you and the others _if_ we still have plans for generating this content in the short term.

**Comment by muhaznazabdi10** [comment]
i don't understand the meaning of prepender in the development of website
using html (challenge)

**Comment by hollenberry** [comment]
@alrightjones 

Awesome questions! I'm not sure about the first and third, but a GraphQL On-Demand Course is actually taking preliminary shape this week during the services-engineering Hack House. I'll contact you with the in-house issue, but if/when this starts to take shape publicly, I'll make sure to @mention you in the relevant threads. 

Also, if you need extra eyes, I'd be interested in joining you and @swinton re:
> I have a few ideas about this and would love to share with you and the others if we still have plans for generating this content in the short term.

**Comment by beardofedu** [comment]
@alrightjones since we shipped an [Introduction to GraphQL](https://services.github.com/on-demand/graphql/) course, do you think we can close this issue out?

cc: @kdaigle just for awareness that we created a GraphQL course!

**Comment by alrightjones** [comment]
@beardofedu absolutely. 🙏
