### ISSUE TITLE
Beautify downloads/index.html

### ISSUE THREAD

**Issue by crichID** [github/training-kit#448]
## Overview

When you build this repository locally (or package it for viewing behind a firewall) the page at on-demand/downloads/index.html looks like this:

![screen shot 2017-01-23 at 10 22 47 am](https://cloud.githubusercontent.com/assets/9950121/22209973/3fdcddfe-e156-11e6-9dd4-ca024a6bbcbe.png)

To improve the offline experience, we should add some formatting to this page to make it look more like the cheat sheets section at https://services.github.com/resources/#cheat-sheets 

### How to Contribute
- [ ] Comment on this issue if you'd like to work/collaborate on it! 
- [ ] Fork the [repository](https://github.com/github/training-kit).
- [ ] Use the [GitHub Flow](https://guides.github.com/introduction/flow/) to make changes to your fork. [This](https://services.github.com/on-demand/intro-to-github/) is a refresher course if you're unsure about how to make a change on GitHub.
- [ ] Push your changes to your repository. 
- [ ] Submit a Pull Request
  - Base Dropdown: github/training-kit
  - Compare Dropdown: Your fork

#### Testing Locally
If you'd like to make and test changes locally (and see how they would look if merged), do the following:
- In your command line:
  - [Install Git](https://git-scm.com/)
  - [Install Ruby](https://www.ruby-lang.org/en/documentation/installation/)
  - [ ] Run `script/setup`
  - [ ] Run `script/server`.
    - When successful, the script will initiate a local server at `http://127.0.0.1:4000/on-demand`.

### Questions?
- Leave a comment on this issue! Make sure to use @ mentions if you want a specific person's attention!

**Comment by Geetus** [comment]
.

**Comment by abdulhannanali** [comment]
@crichID Hey! I can work on this as my first issue!

**Comment by brianamarie** [comment]
@abdulhannanali That's fantastic, thank you! Feel free to fork and open a pull request, and let us know if you need or want any help along the way. 😄

**Comment by abdulhannanali** [comment]
Cool @brianamarie I'll start right away

**Comment by abdulhannanali** [comment]
@brianamarie Some questions before I start.

- Should this downloads page use the layout similar to the other pages using Minimal Mistakes?
- Checking out the [link](https://services.github.com/resources/#cheat-sheets) @crichID mentioned, on what basis are the given icons assigned.
- What's better, An index file maintaining the file paths of all the resources within downloads for every locale or reading the directory to figure out the logic, the indexing based on directory  structure will be flexible but can cause problems, if anything with the path name or the meta data gets wrong, while maintaining a separate index with this data, will be better, but each file would have to be added separately in the index for a given topic?

If there's anything you think I am allowed to figure out myself do let me know. Don't want to bug you with unnecessary questions. Thanks a lot :)

**Comment by brianamarie** [comment]
@abdulhannanali These are all great questions! I'll do my best to answer, but any other @github/services-training members, please feel free to lend your expertise. 😊 



> Should this downloads page use the layout similar to the other pages using Minimal Mistakes?

Minimal Mistakes would be 💯 👍 great. 



> Checking out the link @crichID mentioned, on what basis are the given icons assigned.

Hm...these decisions were made before my time on the training team, so I actually don't know. @crichID Do you have any ideas on this?



> What's better, An index file maintaining the file paths of all the resources within downloads for every locale or reading the directory to figure out the logic, the indexing based on directory structure will be flexible but can cause problems, if anything with the path name or the meta data gets wrong, while maintaining a separate index with this data, will be better, but each file would have to be added separately in the index for a given topic?

I have no strong opinion on this. Maybe @crichID, @stoe, or @hectorsector will have some thoughts?

**Comment by hectorsector** [comment]
> What's better, An index file maintaining the file paths of all the resources within downloads for every locale or reading the directory to figure out the logic, the indexing based on directory structure will be flexible but can cause problems, if anything with the path name or the meta data gets wrong, while maintaining a separate index with this data, will be better, but each file would have to be added separately in the index for a given topic?

@abdulhannanali this depends on your comfort level. I will tell you that in the link @crichID shared, we don't get that fancy, and we just manually maintain the list 😉 If you're into Jekyll and can work through the logic, I'm game! If not (but you're willing to try it out later), I suggest 🚢ing a first iteration with manually added links, and then (if you'd like) we can collaborate on a second iteration using logic.

**Comment by crichID** [comment]
> on what basis are the given icons assigned

@abdulhannanali that is a great question and it was a design decision more than a technical one. We can grab copies of those icons if you would like to reuse them here.

**Comment by hollenberry** [comment]
👋 @abdulhannanali ! 

Just wanted to check in. We're currently running through all of our stale issues and cleaning them up. Are you still interested/do you still have the bandwidth in helping us out with this one? 😄  We'd be happy to support you if you need anything!

**Comment by crichID** [comment]
> Are you still interested/do you still have the bandwidth in helping us out with this one?

Actually @hollenberry I was just looking at this and I think the process is much simpler now.

The goal was to make this page better for offline viewing since resources/downloads lived on services.github.com instead of here on training-kit. Now that resources have been moved back to training-kit, I "think" we can just redirect anything from downloads/ to the resources/cheatsheets.md. @JasonEtco do you agree?

**Comment by JasonEtco** [comment]
> we can just redirect anything from downloads/ to the resources/cheatsheets.md

That would certainly be simpler; as far as I know, the content is the same so I have no problem doing that.

**Comment by learneradarsh** [comment]
I've done downloads/index.html for better user experience (:

**Comment by harry-hov** [comment]
hey, what's the status of this issue @crichID  ?? 
I would like to work on this.

**Comment by brianamarie** [comment]
Hello @harry-hov 👋 I think that this issue should probably be closed. It's my understanding that the downloads page now redirects to cheatsheets, so this is no longer an issue. Sorry for the confusion, and thank you for your willingness to help!
