### ISSUE TITLE
add new locale

### ISSUE THREAD

**Issue by ghaseminya** [github/training-kit#474]
Hi,
I am very happy to translate training-kit cheat-sheet to Persian(IR) locale,
Is there any body that work on it?

**Comment by brianamarie** [comment]
Hi @ghaseminya! That's fantastic! 

If you're willing to translate, the first step would be to fork this repository, and add a directory and markdown file in the `/downloads/` folder, following the structure of the other markdown files. 

Once you've added those files, open a pull request in this repository against the master branch. Please let me know if you need any help!

**Comment by ghaseminya** [comment]
Hi @brianamarie 
Thanks,
I create this file in `/download/fa` directory and translate origin file in it.
https://github.com/ghaseminya/training-kit/blob/master/downloads/fa/

**Comment by brianamarie** [comment]
@ghaseminya Awesome - since there's such great work happening in the pull request, I'm going to close this issue.
