### ISSUE TITLE
Adding the What is GitHub? Video

### ISSUE THREAD

**Issue by crichID** [github/training-kit#477]
## Overview
**TL;DR**
The GitHub video team has created a :sparkles: video to answer the question: What is GitHub? Should we link it on this site?

Video URL: https://youtu.be/w3jLJU7DT5E

## Ideas for places to put it

- In the Path
- On the patchwork page
- At the beginning of the Intro class?

**Comment by brianamarie** [comment]
@crichID 😍 What a great idea! 

> In the Path

I worry it would be redundant if it's also in the intro class, but some may not go through the intro class who are using the path...but it's also a 3 minute video so the risk of repeating it twice doesn't seem that bad. 🤔 

> On the patchwork page

Couldn't hurt! 

> At the beginning of the Intro class

I say yes! 💯
