### ISSUE TITLE
Git Out of Trouble is in Trouble (Broken Links)

### ISSUE THREAD

**Issue by mwiesen** [github/training-kit#499]
@beardofedu @hollenberry 

Very related to #484:

`[Set Up Your Environment](/on-demand/git-trouble/01)` does not resolve to `/git-trouble/git-set-up` as well.

[Here is a search](https://github.com/github/training-kit/search?utf8=%E2%9C%93&q=%2Fon-demand%2Fgit-trouble%2F01&type=) for all occurrences.

[Here](https://services.github.com/on-demand/git-trouble/too-many-commits) is one of the five pages on which the link does not work.

A customer is asking for a fix in [this Zendesk ticket](https://github.zendesk.com/agent/tickets/43343). Thanks a lot in advance!

**Comment by brianamarie** [comment]
cc @github/services-training 

@mwiesen I'm not sure I understand the problem. I tried to replicate based on the instructions in the Zendesk ticket, but wasn't getting broken links. Am I missing something?

![test-broken-link](https://cloud.githubusercontent.com/assets/9906718/24661580/5b291e20-1918-11e7-8614-bb2c06c4481a.gif)

**Comment by brianamarie** [comment]
OH! Of course, after I comment, I see. I understand now, @mwiesen. I will work on fixing this today.

**Comment by mwiesen** [comment]
@brianamarie thanks for the very quick fix! ❤️
