### ISSUE TITLE
Manage several languages in the wiki of a github project

### ISSUE THREAD

**Issue by ckiltolier** [github/training-kit#519]
Hi there

I'd like to manage two languages in [the wiki of the CO2 project](https://github.com/pixelhumain/co2/wiki). Is it possible ?

I didn't find this tip anywhere.

For now my solution is : create two projects : one in french and one in english

Thank you for your answer !

**Comment by brianamarie** [comment]
Hi @ckiltolier! I'm not sure I understand the question. It sounds like you might want to contact the maintainers of that repository and ask them there.

**Comment by crichID** [comment]
@ckiltolier the GitHub wiki's use [gollum](https://github.com/gollum/gollum) so searching their documentation might be a good place to start. All of the documentation we have lives [here](https://help.github.com/categories/wiki/).
