### ISSUE TITLE
Dead link in README.md - self-study.md

### ISSUE THREAD

**Issue by joshmorel** [github/training-kit#524]
The ``/self-study.md`` link in the line below of README.md is dead. Is it redundant because of the link: https://services.github.com/on-demand/path/

>- The recommended [Training Path](https://services.github.com/on-demand/path/) can be found [here](/self-study.md).

**Comment by brianamarie** [comment]
@joshmorel Thank you for opening this issue. I'll work on getting this corrected. 👍
