### ISSUE TITLE
Add html-proofer tests

### ISSUE THREAD

**Issue by stoe** [github/training-kit#547]
We should add [html-proofer](https://github.com/gjtorikian/html-proofer) tests to our `Rakefile` and/or to Travis to test for missing `alt` tags.

See also https://github.com/github/training-kit/pull/535

**Comment by brntbeer** [comment]
> and/or to Travis

@stoe if we add it to the rakefile in `rake:test` it will be run by travis (in other words, there's no "or" option in my opinion). I'm a fan of doing this, it's also helpful for finding broken HTML links in general, not just missing tags

**Comment by brianamarie** [comment]
@stoe Is this similar to https://github.com/github/training-kit/issues/487? I'm happy to close that one out in favor of this issue if it will be more active  👍

**Comment by stoe** [comment]
> if we add it to the rakefile in `rake:test` it will be run by travis (in other words, there's no "or" option in my opinion

Noted, @brntbeer 
I knew that but wanted to leave options, as to probably run it separately.
