### ISSUE TITLE
Add number of contributions to graph 

### ISSUE THREAD

**Issue by brianamarie** [github/training-kit#557]
## Overview
Right now, the contribution graph doesn't state the number of contributions. However, profile contribution graphs do. 

#### Screenshots

<img width="748" alt="screen shot 2017-08-22 at 9 38 21 am" src="https://user-images.githubusercontent.com/9906718/29571096-ec24dc70-871d-11e7-99bf-df9ca4eb0260.png">

#### Reasoning
This would make the graph more accessible to those who may not be able to see the visual but still wish to feel the impact of the number of contributions.

### How to Contribute
- [ ] Comment on this issue if you'd like to work/collaborate on it! 
- [ ] Fork the [repository](https://github.com/github/training-kit).
- [ ] Use the [GitHub Flow](https://guides.github.com/introduction/flow/) to make changes to your fork. [This](https://services.github.com{{site.baseurl}}/intro-to-github/) is a refresher course if you're unsure about how to make a change on GitHub.
- [ ] Push your changes to your repository. 
- [ ] Submit a Pull Request
  - Base Dropdown: github/training-kit
  - Compare Dropdown: Your fork

#### Testing Locally
If you'd like to make and test changes locally (and see how they would look if merged), do the following:
- In your command line:
  - [Install Git](https://git-scm.com/)
  - [Install Ruby](https://www.ruby-lang.org/en/documentation/installation/)
  - [ ] Run `script/setup`
  - [ ] Run `script/server`.
    - When successful, the script will initiate a local server at `http://127.0.0.1:4000{{site.baseurl}}`.

### Questions?
- @hectorsector since you started the contribution graph, do you have any thoughts on this? Also pinging @JasonEtco & @github/services-training for help.

**Comment by hectorsector** [comment]
This should be a fairly simple thing to implement, @brianamarie. Feel free to move it to my column!
