### ISSUE TITLE
Reviewing GraphQL

### ISSUE THREAD

**Issue by crichID** [github/training-kit#577]
### Clean Up Week :tada:

It's clean up week, and my course to review is GraphQL. Here it goes:

- [ ] Remove extra heading at the top of each page

**Introduction to GraphQL**
- [ ] The introduction could stand to be tightened up a little. It seems like we are doing a lot of talking before we get to the point.
- [ ] Rather than starting with links to different apps that have APIs, it might be interesting to use the embedded YouTube video as an example or to embed something else that is pulling from an API (e.g. weather in SF today) **OR** @JasonEtco took this one step further with this idea:
  - Rather than telling them "this is what an API does" it would be really cool to have an interactive tool where they click a button and the tool interactively "pulls" in the data from the API, highlighting each piece of data as it is pulled in.

## This is a work in progress ... will add more!

**Comment by beardofedu** [comment]
Please @ mention me when you are ready for some 👀

**Comment by ebenezergraham** [comment]
This is issue still open? Please @ mention me when you are ready to begin.

**Comment by hollenberry** [comment]
Closing this out since our on demand courses are now deprecated.

Thank you for sharing this idea and starting this work!
