### ISSUE TITLE
Grammar updates to Spanish translation Intro to GitHub

### ISSUE THREAD

**Issue by hectorsector** [github/training-kit#591]
The Spanish translation of _Intro to GitHub_ is [now live](https://services.github.com/on-demand/intro-to-github/es/) 🎉

While I was deploying this internally, @dpmex4527 🙇 suggested a few updates to the Spanish grammar, which I am copying here so it is publicly visible and we can chip away at it.

/cc: @mberasategi since you submitted the initial translation ❤️ 

<img width="570" alt="screen shot 2017-09-15 at 11 12 31 am" src="https://user-images.githubusercontent.com/16547949/30490024-cf9a1dbc-9a06-11e7-9d78-86595815080c.png">
<img width="569" alt="screen shot 2017-09-15 at 11 12 20 am" src="https://user-images.githubusercontent.com/16547949/30490022-cf95f8fe-9a06-11e7-89ce-2f1dc39aa979.png">
<img width="569" alt="screen shot 2017-09-15 at 11 12 09 am" src="https://user-images.githubusercontent.com/16547949/30490021-cf95ba92-9a06-11e7-95d2-6fea82942710.png">
<img width="567" alt="screen shot 2017-09-15 at 11 12 03 am" src="https://user-images.githubusercontent.com/16547949/30490023-cf964cdc-9a06-11e7-83ff-373fbaaa4b07.png">
<img width="578" alt="screen shot 2017-09-15 at 11 11 54 am" src="https://user-images.githubusercontent.com/16547949/30490020-cf957514-9a06-11e7-9c00-c06e563e1dc0.png">
<img width="577" alt="screen shot 2017-09-15 at 11 11 46 am" src="https://user-images.githubusercontent.com/16547949/30490019-cf94b192-9a06-11e7-902d-3c883a56be2a.png">

### How to Contribute
- [ ] Comment on this issue if you'd like to work/collaborate on it!
- [ ] Fork the [repository](https://github.com/github/training-kit).
- [ ] Use the [GitHub Flow](https://guides.github.com/introduction/flow/) to make changes to your fork. [This](https://services.github.com/on-demand/intro-to-github/) is a refresher course if you're unsure about how to make a change on GitHub.
- [ ] Push your changes to your repository.
- [ ] Submit a Pull Request
  - Base Dropdown: github/training-kit
  - Compare Dropdown: Your fork

#### Testing Locally
If you'd like to make and test changes locally (and see how they would look if merged), do the following:
- In your command line:
  - [Install Git](https://git-scm.com/)
  - [Install Ruby](https://www.ruby-lang.org/en/documentation/installation/)
  - [ ] Run `script/setup`
  - [ ] Run `script/server`.
    - When successful, the script will initiate a local server at `http://127.0.0.1:4000/on-demand`.

### Questions?
- Leave a comment on this issue! Make sure to use @ mentions if you want a specific person's attention!

**Comment by mberasategi** [comment]
Hi @hectorsector and @dpmex4527 ,

I agree with some corrections, not with some others. How should I proceed? I may do the changes and create a new pull request? Discuss them here individually...?

**Comment by beardofedu** [comment]
@mberasategi If you have any concerns about some of the changes suggested, I think you can discuss them here or within the pull request that you have open in your fork. 👍
