### ISSUE TITLE
Invalid invites for training repo

### ISSUE THREAD

**Issue by abdulajet** [github/training-kit#611]
## Overview
**TL;DR**
The intro to GitHub training [repo](https://github.com/githubschool/open-enrollment-classes-introduction-to-github/issues/) was sending invalid invites.

### Extra Detail
I was running a session to walk beginners through the introduction to GitHub training. When they created new issues to get added as a collaborator they received an invite from teacher bot but all of the invites were invalid. My invite seemed to work. @hectorsector pointed me here.

**Comment by hollenberry** [comment]
@abdulajet thank you so much for flagging this to our attention last year. Thanks to your ping, we were able to take action internally and change up a few items so that invitations were, again, valid. 

Closing this out as a success!

**Comment by abdulajet** [comment]
Dope! Great job team 😄
