### ISSUE TITLE
Can I add other language apart from English and Español ?

### ISSUE THREAD

**Issue by keangkai** [github/training-kit#622]
I want to add other language.
Is OK ?

**Comment by hectorsector** [comment]
Of course, @keangkai! The process isn't very well documented but I'm happy to work with you on _how_ to do it if you start translating.

**Comment by beardofedu** [comment]
@keangkai just to get some visibility on this translation, what language were you hoping to translate the content to?

**Comment by milesibastos** [comment]
That is a good sample how to getting started.
https://github.com/github/training-kit/pull/610/files

**Comment by peterparkers** [comment]
that's great
but what language were you want to do.

**Comment by keangkai** [comment]
Thank you everybody.I want to add Thai language

**Comment by pingping-n** [comment]
@keangkai Just make it. I will work together with you guy.

**Comment by perryken** [comment]
hmmmmmmmm

**Comment by brianamarie** [comment]
If anyone is still interested and needs some help getting started, please ask for help and @github/services-training will do our best to support you.

**Comment by ppremk** [comment]
#624

**Comment by ppremk** [comment]
@keangkai thank you for the initiative, is there any progress for this issue? 🙂

**Comment by hollenberry** [comment]
Closing this out since our on demand courses are now deprecated.

Thank you for sharing this idea and starting this work!
