### ISSUE TITLE
It's error in console

### ISSUE THREAD

**Issue by keangkai** [github/training-kit#627]
Uncaught TypeError: Cannot read property 'firstChild'

**Comment by beardofedu** [comment]
@keangkai what is prompting the error? Can you provide a screenshot of the error?

**Comment by Baimaikp** [comment]
i want review too

**Comment by keangkai** [comment]
![screen shot 2560-12-14 at 5 07 59 pm](https://user-images.githubusercontent.com/26068886/33986837-65d66516-e0f1-11e7-99a6-e303448f5d61.png)

**Comment by denmch** [comment]
This is related to the Google Maps API, and it looks like it can't find the element it wants to work on. The file at `on-demand/assets/js/mapsAPI.js` is looking for `#map`, which doesn't exist on this page. I think the map is only used on the subpage at `/on-demand/intro-to-github/`.

**Comment by brianamarie** [comment]
This was resolved by #631. Many thanks to @denmch for fixing it, and finding me on Twitter to make sure this issue is properly closed. Apologies for missing it and keeping it open.
