### ISSUE TITLE
More `git diff` and `git log` in on-demand

### ISSUE THREAD

**Issue by brianamarie** [github/training-kit#629]
## Overview
**TL;DR**
We should add more `git log` and `git diff` to our courses.

### Extra Detail

@bas brought up a great point while we were chatting in Amsterdam, that the courses now tell users to type `git log` but the users aren't given much explanation on what they should look for. It would be helpful to have more `git log` and `git diff` within the courses, along with explanations of what to expect and what it means. 

@github/services-training what do you think?

**Comment by hollenberry** [comment]
Closing this out since our on demand courses are now deprecated.
