### ISSUE TITLE
Retire active on-demand repositories

### ISSUE THREAD

**Issue by brianamarie** [github/training-kit#646]
## Overview
https://lab.github.com/ has replaced on-demand as GitHub Training's recommendation for self paced learning. While the resources can still stay available, we would like to archive the interactive repositories and the directions pointing to them. We would only need to focus our action on those courses which have corresponding repositories. 

This comes from @hectorsector's request in Slack to restart the conversation and get some help phasing out the on-demand courses which we aren't maintaining as actively as we were in the past. 

### Next steps 
- [ ] Reach agreement on the rest of these steps @github/services-training @crichID @hollenberry @ppremk @a-a-ron @hectorsector @beardofedu 
- [ ] Identify which courses link to specific interactive repositories
- [ ] Add links to all on-demand courses pointing to learning lab
- [ ] Amend directions to either A) note that those repositories are no longer active, and users should fork them and continue the activities on their own, or B) another option 
- [ ] Comment on and close all open issues and pull requests in active repositories
- [ ] Archive repositories

**Comment by a-a-ron** [comment]
I agree with the outlined steps. In my opinion, fully retiring on-demand and directing all traffic to LL is the best path forward so i'm on board with that. 

> Amend directions to either A) note that those repositories are no longer active, and users should fork them and continue the activities on their own

Yes. I think content is still valuable, especially the graphql content that we currently don't have a replacement for on LL. Allowing read-only versions to be forked for individual purposes is still valuable. We just need to clearly express that support/responses will no longer be provided. 

Happy to ✋ with moving this forward

**Comment by ppremk** [comment]
> I agree with the outlined steps. In my opinion, fully retiring on-demand and directing all traffic to LL is the best path forward so i'm on board with that.

I too agree on this

> Allowing read-only versions to be forked for individual purposes is still valuable. We just need to clearly express that support/responses will no longer be provided.

💯 agreed as well on this

**Comment by brianamarie** [comment]
@ppremk @a-a-ron, awesome, thank you! 👍 

@crichID @hollenberry @hectorsector @beardofedu Does this plan seem OK? Mostly, are there any objections before we can move forward?


> Happy to ✋ with moving this forward

@a-a-ron Once we either (A) get some more 👍, or (B) a few more days pass to give the chance for more critical feedback and other ways to move forward, I think it would be 💯 if you moved forward with this. Thank you! ✨

**Comment by hectorsector** [comment]
Looks good, @brianamarie @a-a-ron

**Comment by mberasategi** [comment]
Hi! Sorry to jump in from a probably foreign field (and language), but let me express my concerns in the hopes that there is a way out I just don't know about/haven't thought of.

I'm a teacher in higher education using the on-demand courses as a way to introduce my students to GitHub. Having that material in their mother tongue (Spanish) is a requirement and so I translated 101 and 102 last year.

I was now planning to translate the CLI path, but having read this... I have no special attachment to the on-demand courses (other than it took some time to get them translated) and will certainly check Labs to see if it can work with my students. However having that in Spanish is still a requirement, and I have no objection to do the translation myself if it gets pushed to the production website somehow. 

Any (fairly short-term) plans on this, having Labs translated? Other solutions to a situation like this?

Thanks in advance!

**Comment by mberasategi** [comment]
Sorry to push on this, but @brianamarie or @hectorsector , I need to sort this out ASAP because the classes have started already. Any chance to contribute translations to Lab courses? I would be more than happy to do that (as I did with the on-demand courses) but would need to begin right away. Thanks again!

**Comment by brianamarie** [comment]
This is great information to have - @github/services-training, let's commit to not breaking anything that currently exists until we have a Spanish replacement that would be functional (or possibly an improvement) for @mberasategi. 

@mberasategi, does this sound OK? I think we would love to have multiple language support on Learning Lab, but as you're depending on this resource in on-demand, we definitely don't want to leave you without a resource that you were planning on using.

**Comment by mberasategi** [comment]
@brianamarie that would do it for me 👌  

I will keep using on-demand this Fall then (maybe keep on translating, I wanted to use the CLI this time &mdash; any chance to get this pushed?), and let me know when translations for Learning Lab are an option. Count on me for Spanish!

**Comment by brianamarie** [comment]
I'm going to close this issue for now. @github/services-training, let's revisit this, and also remember the importance of translations in our resources.
