### ISSUE TITLE
Invalid link in CONTRIBUTING.md

### ISSUE THREAD

**Issue by paluchnuggets** [github/training-kit#675]
## Overview
![Screenshot 2019-04-19 at 17 34 01](https://user-images.githubusercontent.com/41453558/56431505-30041300-62ca-11e9-9dcb-9b74c2c687cc.png)

In the picture above I have cricled link that does not work. Due to that I am not sure how to follow that guide exactly. I am eager to prepare translation to polish language 😄  
 
![Screenshot 2019-04-19 at 17 44 40](https://user-images.githubusercontent.com/41453558/56431784-55dde780-62cb-11e9-922b-0d27dbbaf381.png)

I assume that this is that file where translated resources should be added but I would like to receive a confirmation. If yes, I could correct that link.

**Comment by globefire** [comment]
I would like to make the above change.

**Comment by Amintorialay** [comment]
😛😛😛😛😛😟

torialay amin

**Comment by brntbeer** [comment]
hey @paluchnuggets sorry for the delay. I can see in #678 that the polish translation was already added, effectively closing out this issue.

@globefire if you would like to create a new Pull Request to update https://github.com/github/training-kit/blob/master/CONTRIBUTING.md by making it link to https://github.com/github/training-kit/blob/master/index.html, that would be an awesome contribution to keep these documents up to date!
