### ISSUE TITLE
Draft structure of the GitHub Action Cheat Sheet

### ISSUE THREAD

**Issue by helaili** [github/training-kit#691]
Topics: 

- About
- Syntax overview
- Events
- Pattern matching
- Jobs
- Steps
- Strategies
- Run
- Secrets
- Context variables

![github-action-cheat-sheet](https://user-images.githubusercontent.com/2787414/64184472-c9902380-ce6b-11e9-969f-3429842521a2.png)

**Comment by brianamarie** [comment]
This is great! @johndavidmarx @hectorsector and @mattdavis0351 are working on materials for more Actions Learning Lab courses, as well as Actions curriculum for in-person training, and the DevOps certification. cc @johndavidmarx @hectorsector @mattdavis0351 for 👀eyes on this Action cheat sheet in progress by @helaili 🎉

**Comment by bdougie** [comment]
Hello, I only learned of https://github.com/github/training-kit/pull/692 through this comment yesterday https://github.com/github/developer-relations/issues/255#issuecomment-556127637 -- so please do not take my comments as blocking anything but some observations for the existing content (which is understood to be incomplete). 

I am leaving my comment here to avoid de-railing the active review process that is already in progress. I love that this is in progress and would love to assist in sharing/consuming the final draft of the cheat sheet.  

## My experience with teaching Actions
I have conducted some [Actions workshops](https://github.com/github/developer-relations/issues/228), Online [Twitch Streams](https://www.learnwithjason.dev/taking-action-with-github-actions), in-person [Action Hackspace at Universe](https://github.com/github/universe/issues/691) and have found the following issues with users getting started with Actions.

1. Debugging is hard and requires you to push or re-trigger actions to find out small and minute details from the environment.
2. The current Action docs, though still a WIP, are hard to traverse and find things (I would hate to translate the docs 1:1) on to a handout. The doc block that shows when editing workflows in the UI is an excellent example of a cheat sheet. 
3. Finding out essential details about Action environments is possible but requires a lot of trial and error. 

## Content direction or story
Perhaps the content can get a little more concise and address 2 & 3 from above by answering the more common problems. The current git cheatsheet does this well by providing some but not all of the standard git commands.

For examples of a concise story, as mentioned above, the lab courses are great examples and would great examples for the handouts. 

- [Hello, GitHub Actions!](https://lab.github.com/github/hello-github-actions!)
- [GitHub Actions: Continuous Delivery](https://lab.github.com/githubtraining/github-actions:-continuous-delivery)

## A suggestion for simplification
The current state of the GitHub Actions cheat sheet is dense with content. There is an opportunity for simplification by highlighting the below on the first page or above the fold. 

1. Show only 1 or 2 workflows, I recommend a variation(s) on the "hello world" format. 
   - Make the yaml example a "Hello World." My thought is that yaml is not intuitive for those not familiar and having a story to the examples will assist with quickly finding what they need.
   - Perhaps tie the `echo "A little bit more action"` example with the other flags: i.e. switch the `branch` in the example to master and update the `run` to `echo "You just pushed to the master branch"`

With the understanding that the content is not complete, I did have some other suggestions: 
1. make the glossary of words secondary (The definitions take up a lot of space). 
   - Limit the glossary of the keywords to the more common: [name, on, jobs, needs, steps, run].
2. Only list the common event/webhook types with descriptions [push, pull_request, issue, schedule, uses]
3. Only list some environment variables i.e. [GITHUB_ACTOR, GITHUB_REF, GITHUB_REPOSITORY]

## Possible next steps
I would love to hear if any of the above is in line with the direction of the project. I will await confirmation before commenting directly on the PR.

**Comment by helaili** [comment]
Thank you for this great comment @bdougie 🙇 

I agree there is a lot to be changed in the current version as I have been more focused on the creation process than the content itself. This is why I'm transferring this work to [github/actions-cheat-sheet](https://github.com/github/actions-cheat-sheet) where the PDF is automatically generated with GitHub Actions 😄 based on an AsciiDoc file. This will give us a lot more flexibility to amend the content and provides an easy way to have a 2-pager and a 1-pager. 

So please, feel free to comment on github/actions-cheat-sheet#5 as I now want to refocus on the content. I'd suggest we wrap up the two pager first, and then add a one-pager.

**Comment by brianamarie** [comment]
Hi @helaili! I'd love to take a look at the actions cheat sheet, but I'm not able to access it. If it's private, would you mind giving me access? Also, are you considering having the cheat sheet be open source?

**Comment by helaili** [comment]
Fantastic @brianamarie! The repo was meant to be public, it's now fixed. 
I'm still working on the content and the README needs some work too.
