### ISSUE TITLE
Is there something wrong with description of "git  log --follow [file]"?

### ISSUE THREAD

**Issue by kevinfszu** [github/training-kit#759]
## Overview
There is something wrong with description of "git  log --follow [file]".

#### Reasoning
the `--follow` option in [documentation of Git](https://git-scm.com/docs/git-log) :
![image](https://user-images.githubusercontent.com/5536550/88245412-ab245800-ccc9-11ea-94fe-c620635f81bf.png)

But the meaning of the `--follow` in this repository is inverse:
![image](https://user-images.githubusercontent.com/5536550/88245354-816b3100-ccc9-11ea-8ee8-a497203c4d6a.png)

**Comment by brianamarie** [comment]
Thank you for opening this issue, @kevinfszu. This has been corrected in the plain text version, but we do need to make updates to the PDF. cc @github/ps-programs, I'm going to put this on the triage board.
