### ISSUE TITLE
docs/install_linux.md

### ISSUE THREAD

**Issue by kkash18** [github/training-kit#817]
![1f31c.png](https://user-images.githubusercontent.com/77268170/107950754-cf44d080-6f5c-11eb-902b-8060dc2cb1ef.png)

**Comment by brianamarie** [comment]
Hi @kkash18, I am going to close this issue like I have closed the previous issues that you have opened. We welcome issues, comments, and pull requests in this repository, but please refrain from opening issues or other communications that are not relevant to this repository or its purpose.
