### ISSUE TITLE
How to Contribute-Testing Locally

### ISSUE THREAD

**Issue by totongcute** [github/training-kit#834]
#825 

### How to Contribute
- [x] Comment on this issue if you'd like to work/collaborate on it!
- [x] Fork the [repository](https://github.com/github/training-kit).
- [x] Use the [GitHub Flow](https://guides.github.com/introduction/flow/) to make changes to your fork. [This](https://lab.github.com/githubtraining/introduction-to-github) is a refresher course if you're unsure about how to make a change on GitHub.
- [x] Push your changes to your repository.
- [x] Submit a Pull Request
  - Base Dropdown: github/training-kit
  - Compare Dropdown: Your fork

#### Testing Locally
If you'd like to make and test changes locally (and see how they would look if merged), do the following:
- In your command line:
  - [Install Git](https://git-scm.com/)
  - [Install Ruby](https://www.ruby-lang.org/en/documentation/installation/)
  - [x] Run `script/setup`
  - [x] Run `script/server`.
    - When successful, the script will initiate a local server at `http://127.0.0.1:4000/`.

### Questions?
- Leave a comment on this issue! Make sure to use `@mentions` if you want a specific person's attention!

**Comment by brianamarie** [comment]
Hello 👋🏻 It looks like you may be practicing using GitHub. That's great! But, this repository is in active use, and this may be distracting those who maintain it. I'm going to close this, but if you'd like to suggest a bug fix or feature, please open a new issue with the context and information in the body. Thanks!
