### ISSUE TITLE
If you view a transaction that is either just a fake TXID or a new one that hasn't been processed yet instead of saying it's invalid it shows the information for a random TX in the database.

### ISSUE THREAD

**Issue by totongcute** [github/training-kit#837]
If you view a transaction that is either just a fake TXID or a new one that hasn't been processed yet instead of saying it's invalid it shows the information for a random TX in the database.

![image](https://user-images.githubusercontent.com/7625236/75612407-083c2900-5af1-11ea-8a5a-e72338448282.png)

__Originally posted by @Crypto2 in https://github.com/ethereumclassic/explorer/issues/331__

**Comment by hectorsector** [comment]
Hello :wave: It looks like you may be practicing using GitHub. That’s great! But, this repository is in active use, and this may be distracting those who maintain it. I’m going to close this, but if you’d like to suggest a bug fix or feature, please open a new issue with the context and information in the body. Thanks!
