### ISSUE TITLE
Checked a balance on http://etherhub.io one address, where there are more than 8 txs, but can see only 8 txs. I don't want to share the address here, as it is public here ;-). If you want the address just pm me on etc discord (a.s.). Thx.

### ISSUE THREAD

**Issue by totongcute** [github/training-kit#838]
Checked a balance on http://etherhub.io one address, where there are more than 8 txs, but can see only 8 txs. I don't want to share the address here, as it is public here ;-). If you want the address just pm me on etc discord (a.s.). Thx.

__Originally posted by @TheEnthusiasticAs in https://github.com/ethereumclassic/explorer/issues/319__

**Comment by brianamarie** [comment]
Hello 👋🏻 It looks like you may be practicing using GitHub. That's great! But, this repository is in active use, and this may be distracting those who maintain it. I'm going to close this, but if you'd like to suggest a bug fix or feature, please open a new issue with the context and information in the body. Thanks!
