### ISSUE TITLE
Instagram password cracker

### ISSUE THREAD

**Issue by Ceazerbrowns** [github/training-kit#854]

**Comment by ASNAS557** [comment]
> provided

hazna_hajaz__

**Comment by brianamarie** [comment]
Hello 👋🏻 It looks like you may be practicing using GitHub. That's great! But, this repository is in active use, and this may be distracting those who maintain it. I'm going to close this, but if you'd like to suggest a bug fix or feature, please open a new issue with the context and information in the body. Thanks!

**Comment by Kalihacker134** [comment]
Hack Instagram password

**Comment by melodyjay** [comment]
hi guys... am sorry I wasn't able to go for the fix....my computer broke down in the process but am to get this done as quick as possible.
