### ISSUE TITLE
Site does not work (404)

### ISSUE THREAD

**Issue by phil-blain** [github/training-kit#862]
## Overview
**TL;DR**
<One to two sentence description of the issue you are encountering or trying to solve.>

Navigating to https://github.github.com/training-kit/ redirects to https://training.github.com/ and this yields a 404.

**Comment by hectorsector** [comment]
Should be fixed in #861 -- thanks for flagging it @phil-blain. Sometimes, GitHub Pages will cache the 404 so, if it does, it'll work again after a while!
